DEFINE
	VAR __DS0FilterTable = 
		TREATAS({"Accessories"}, 'Product'[Category])

	VAR __DS0FilterTable2 = 
		TREATAS({"'Sales'[Mes_Sales]"}, 'KPI Selector'[KPI Selector Champs])

	VAR __DS0FilterTable3 = 
		TREATAS({"FY2020"}, 'Date'[Year])

EVALUATE
	SUMMARIZECOLUMNS(
		__DS0FilterTable,
		__DS0FilterTable2,
		__DS0FilterTable3,
		"Mes_Sales", IGNORE('Sales'[Mes_Sales]),
		"Mes_KPI_Remaining", IGNORE('Table'[Mes_KPI_Remaining])
	)